[project]
name = "holding-pattern"
version = "0.1.0"
description = "a template for dependency only packages"
requires-python = ">=3.12"
dependencies = [ ]

[build-system]
requires = ["uv_build>=0.9.0,<0.10.0"]
build-backend = "uv_build"
